R_AND = "全大写的 AND，读音程序会一个字母一个字母地念（A、N、D），和录音里说的 and 对不上"
EDITS = [
 (92, "famous writer?", "famous writer.", "这里不是问句（是改好的定语从句），问号会让模型学成问句的上扬语调"),
 (637, "is JimWho is", "is Jim。Who is", "两个英文单词粘在一起了（Jim 和 Who），中间要断开"),
 (647, "AND的第二种", "and的第二种", R_AND),
 (649, "AND的第二个", "and的第二个", R_AND),
 (654, "只能用AND来", "只能用and来", R_AND),
 (656, "以上是AND只", "以上是and只", R_AND),
 (657, "如果AND前后", "如果and前后", R_AND),
 (663, "的是，AND在", "的是，and在", R_AND),
 (664, "就是AND最主要", "就是and最主要", R_AND),
 (664, "使用AND的时候", "使用and的时候", R_AND),
 (670, "并且AND的", "并且and的", R_AND),
 (927, "而AND就", "而and就", R_AND),
 (938, "都不想要好。以上", "都不想要。好，以上", "「好」是下一句开头的口头禅，句号放错了地方"),
 (946, "text me?", "text me.", "这里不是问句（是陈述句），问号会让模型学成问句的上扬语调"),
]
UNSURE = [
 (8, "他所带着的信息", "他所代替的信息（或：代指的）", "「所带着的信息」不太通，第11行说的是「所代替的信息」"),
 (101, "就是that person", "就是that person's", "上一句刚说 his 的意思是 that person's"),
 (157, "The game that I play is interesting.", "The game they are playing is interesting.", "上一句例句是 The game which they are playing is interesting，省略 which 后应该只少 which"),
 (172, "造成定语从句", "改造成定语从句", "别处都说「改造成定语从句」"),
 (198, "anyone of your family", "anyone in your family", "标准说法是 anyone in your family；也可能就是这么说的"),
 (199, "who is the doctor", "who is a doctor", "上下文的例句是 who is a doctor"),
 (215, "who is the doctor", "who is a doctor", "同上"),
 (219, "因为in that不能", "因为that不能", "in 本身就是介词，「in that 不能和介词一起放句首」说不通；最初识别出来的也是「因为that不能」（上次是按母本改成 in that 的）"),
 (225, "that Frank remember in the school.", "that Frank remembers in the school.", "母本写的是 Let Frank…；remember 后面有没有 s 也请听"),
 (255, "必须使用关系代词的情况", "必须使用关系代词that的情况", "前后都说「关系代词that」"),
 (275, "your dog is not puppy", "your dog is not the puppy", "可能少了 the"),
 (281, "They called Jason Hero", "They called Jason a hero", "可能少了 a"),
 (323, "这个语句", "这个例句", "整篇都说「例句」，「语句」只有这一处"),
 (403, "A ready player when we are, where people can do many things, feels quite real.", "可能是 In Ready Player One, VR, where people can do many things, feels quite real.", "上一句说到《头号玩家》和 VR；原句看不出来"),
 (409, "思考的情况，", "思考的情况下，", "「在……的情况下」可能漏了「下」"),
 (424, "虽然说很明显", "所以说很明显", "「虽然」后面没有「但是」，这里是在下结论"),
 (429, "He主语", "He是主语", "可能少了「是」"),
 (495, "名词性从句was in the box", "名词性从句what was in the box", "可能少了 what"),
 (530, "quiet的构成", "quiet所构成", "下面几行都说「由……所构成」"),
 (560, "独立于存在于", "独立存在于", "多了一个「于」；也可能是说到一半改口"),
 (583, "那个男生Jim", "那个男生是Jim", "第585行是「那个正在说话的男生是Jim」"),
 (644, "翻译并且", "翻译为并且", "别处都说「翻译为」，可能漏了「为」"),
 (707, "炸薯条就是fish and chips", "炸鱼薯条就是fish and chips", "fish and chips 是「炸鱼薯条」"),
 (730, "就指向Johnny is a rich man", "就只剩下Johnny is a rich man", "第733行同样的讲法是「就只剩下了」"),
 (753, "but actually Scheming", "but is actually scheming", "合并时只去掉重复的 she，is 应该留下"),
 (772, "a disliked wish always criticizes me", "I dislike the way she always criticizes me", "牛津词典的例句，读音也对得上"),
 (932, "neither students nor", "neither the students nor", "第933行说「第一个是the students」"),
 (950, "She never called nor text me.", "She neither called nor texted me.", "前面说用 neither…nor 来重写"),
 (956, "or被翻译或者还是", "or被翻译为或者还是", "可能漏了「为」（第962、963行都说「翻译为」）"),
 (967, "不但使用连词or", "不再使用连词or（或：不能 / 不是）", "意思是不用 or、继续用 and，「不但」说不通"),
 (975, "写作业如果不妥协", "写作业如果不做 / 不完成", "「不妥协」有点怪；也可能就是原话"),
]
def INTRO(total, n, u, p):
    return [
        (f'第二次校对结果（{total} 句）', True, None),
        ('', False, None),
        ('你按上次清单改的 37 句都改对了（只有第 673 句「会想得」没改，这一句标了「不用（太短）」，不参加训练，不改也没关系）。', False, None),
        (f'这次又查出 {n} 句要改（黄色，改过的字红色加粗）：主要是全大写的「AND」（读音程序会念成 A、N、D 三个字母）、不是问句却打了问号、两个英文单词粘在一起。', False, 'Y'),
        (f'没把握、没有改的 {u} 处（浅蓝色）：请听录音再决定，不听也可以先不管。', False, 'B'),
        ('', False, None),
        (f'在程序里怎么改：看「在程序里怎么改」那一页，{p} 条，照着在校对表的「查找 / 替换」里点「全部替换」，最后点「保存修改」和「✅ 确认训练素材」。', False, None),
    ]
