# 改动清单：MASTER = 按母本整句改；EDITS = 片段替换 (行号, 原来, 改成, 原因)；UNSURE = 没改、请听录音
MASTER = {
 38: "「受人尊重的类人」少了「那」",
 173: "「位置」是 which 听错了",
 210: "按母本：非限定定语从句",
 212: "「位置」是 which 听错了",
 219: "「定语重句 / 重剧」→「定语从句」；母本是「因为in that不能」",
 223: "「行词」→「先行词」；少了「有」",
 268: "「定语层」→「定语从句」",
 344: "「envig」是 in which 听错了",
 401: "「定语」是「电影」听错了（头号玩家是电影）",
 402: "「定语」是「电影」听错了",
 404: "「定语」是「电影」听错了",
 465: "「行词」→「先行词」",
 509: "按母本：句首有「那」",
 581: "「EnableCode」是 in a blue coat 听错了",
 628: "「行词」→「先行词」",
 635: "「行词」→「先行词」",
 655: "「这包的Apple Sand Bread」是 She bought apples and bread 听错了",
 703: "「r」是 are，「a字」是 is",
 721: "英文例句听错了：she bought apples and she bought bread；「并列句子」→「并列句」",
 759: "「nlbluecode」是 in a blue coat，「varying」是 wearing，「从旧」→「从句」",
 789: "「户」是 who；「从语」→「从句」",
 802: "「虽然说」→「所以说」（按母本，意思才通）",
 820: "「行词」→「先行词」",
 836: "「户和户母」是 who 和 whom；「移音到词」→「引导词」",
 846: "「行词」→「先行词」",
 847: "「行词」→「先行词」（两处）",
 853: "「定语程序」→「定语从句」；「户或户母」是 who 或 whom",
 903: "「极无动词」→「及物动词」；「例子」→「例句」；英文是 Jason lives in a small city",
 914: "按母本：句首有「好，」",
 932: "「定语」是「电影」听错了",
 935: "「undernaut」是 neither nor；「主义」→「主语」；「连接词」→「连词」",
 955: "「all」是 or 听错了（这一节讲 or）",
}
EDITS = [
 (652, "用&去连接", "用and去连接", "「&」就是 and，写成英文单词"),
 (661, "合编在一起", "合并在一起", "「合编」是「合并」听错了"),
 (661, "用&连接起来", "用and连接起来", "「&」就是 and，写成英文单词"),
 (673, "会想得非常不自然", "会显得非常不自然", "「想得」是「显得」听错了（第709行也是「会显得非常不自然」）"),
 (849, "关于代词", "关系代词", "「关于代词」是「关系代词」听错了"),
 (849, "先行词的提升", "先行词的替身", "「提升」是「替身」听错了（第444、449行都说关系代词是先行词的「替身」）"),
 (923, "相当于是链磁", "相当于是连词", "「链磁」是「连词」听错了"),
]
UNSURE = [
 (101, "就是that person", "就是that person's", "上一句刚说 his 的意思是 that person's，这里可能少了 's"),
 (157, "The game that I play is interesting.", "The game they are playing is interesting.", "上一句的例句是 The game which they are playing is interesting，省略 which 以后应该只少一个 which；母本里也是 that I play，所以没改"),
 (172, "造成定语从句", "改造成定语从句", "别处都说「改造成定语从句」（612、625、631行），可能少了「改」；也可能你就是这么说的"),
 (199, "who is the doctor", "who is a doctor", "上下文的例句是 I have a sister who is a doctor（198、213行都是 a doctor）"),
 (215, "who is the doctor", "who is a doctor", "同上一条，a 和 the 很容易听混"),
 (225, "that Frank remember in the school.", "that Frank remembers in the school.", "母本写的是「Let Frank remember…」，但这里讲的是 that 引导定语从句，识别出来的 that 更像原话；所以这一句没按母本改。remember 后面有没有 s 也请听一下"),
 (255, "必须使用关系代词的情况", "必须使用关系代词that的情况", "前后几种情况都说「关系代词that」，可能少了 that；也可能你就是这么说的"),
 (275, "your dog is not puppy", "your dog is not the puppy", "同样的句型别处都带 the，可能少了 the"),
 (281, "They called Jason Hero", "They called Jason a hero", "原句应该是 They called Jason a hero，可能少了 a"),
 (403, "A ready player when we are, where people can do many things, feels quite real.", "可能是 In Ready Player One, VR, where people can do many things, feels quite real.", "上一句刚说到电影《头号玩家》(Ready Player One) 和 VR；原句看不出来"),
 (495, "名词性从句was in the box", "名词性从句what was in the box", "可能少了 what"),
 (583, "那个男生Jim", "那个男生是Jim", "第585行同样的句子是「那个正在说话的男生是Jim」，可能少了「是」"),
 (707, "炸薯条就是fish and chips", "炸鱼薯条就是fish and chips", "fish and chips 是「炸鱼薯条」，可能少了「鱼」；也可能你就是说的「炸薯条」"),
 (730, "就指向Johnny is a rich man", "就只剩下Johnny is a rich man", "第733行同样的讲法是「那就只剩下了…」"),
 (772, "a disliked wish always criticizes me", "I dislike the way she always criticizes me", "下一句说这个例句来自牛津词典、先行词是 way；牛津词典里正好有这个例句，读音也对得上"),
 (923, "按E10 Apple", "可能是 I eat an apple（或 Ann eats an apple）", "下一句讲宾语 apple，第925行合并成 an apple and an orange"),
 (932, "neither students nor", "neither the students nor", "第933行说「第一个是the students」，可能少了 the（这一句的「电影」已经改好了）"),
 (950, "She never called nor text me.", "She neither called nor texted me.", "前面说用 neither…nor 这个句式来重写；母本里也是 never…nor，所以没改"),
 (967, "不但使用连词or", "不再使用连词or（或：不能 / 不是）", "意思是「不用 or，而是继续用 and」，「不但」说不通"),
 (975, "写作业如果不妥协", "写作业如果不做 / 不完成", "「不妥协」读起来有点怪；也可能就是原话"),
]
