from common import *
cfg, project = voice(["今天王芳同学在教是里看书", "下面我们来看第二个例子"])
fake_engine({"c000": "今天黄芳同学在教室里看书", "c001": "下面我们来看第二个例子"})
pc.find_suspects(project, cfg)
show(project, "c000", "auto")
review.adopt_suggestion(project, "c000")
show(project, "c000", "adopted")
review.set_draft(project, "c000", text="今天王芳同学在教室里看书")   # teacher reverts only 黄→王
print("rejected:", review.load_rejected(project))
review.save_rows(project)
review.set_draft(project, "c000", text="今天王芳同学在教是里看书")   # and later types 是 back too (to see 室 suggestion again? it is also rejected now)
print("rejected:", review.load_rejected(project))
review.save_rows(project)
pc.find_suspects(project, cfg)
show(project, "c000", "after 🔍")
# partial: only 王 rejected, 室 should still be suggested
cfg, project = voice(["今天王芳同学在教是里看书", "下面我们来看第二个例子"])
fake_engine({"c000": "今天黄芳同学在教室里看书", "c001": "下面我们来看第二个例子"})
pc.find_suspects(project, cfg)
review.adopt_suggestion(project, "c000")
review.set_draft(project, "c000", text="今天王芳同学在教室里看书"); review.save_rows(project)
review.set_draft(project, "c000", text="今天王芳同学在教是里看书", remember=False); review.save_rows(project)
print("rejected:", review.load_rejected(project))
pc.find_suspects(project, cfg)
show(project, "c000", "partial after 🔍 (want 是→室 kept, 王→黄 gone)")
